version: "3"
services:
    boxmetrics:
        image: "boxmetrics:dev"
        build:
            context: .
            dockerfile: Dockerfile
        hostname: boxmetrics
        stdin_open: true
        tty: true
        working_dir: '/boxmetrics-dev'
        volumes:
            - ".:/boxmetrics-dev"
